In [270]:
%reset -f

In [271]:
%connect_info

{
  "shell_port": 57679,
  "iopub_port": 43945,
  "stdin_port": 37933,
  "control_port": 58981,
  "hb_port": 41023,
  "ip": "127.0.0.1",
  "key": "78a1e733-d7ffb6cdb941689802201b86",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-d3dda29b-ebe9-46c6-932c-7aabf2b07e56.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.

In [272]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import itertools

In [273]:
dir_data = "run1_combined_cleaned_noCnoA/"
path_base = "/home/trix_arch/IIVspace/DataSc/"+\
            "DataCamp2021/DSR_B28_work/DSR28_portfolio_project/"+\
            "Measurements_n_Tests/GGS_arduino_readings/GGSv2I_complete/"
pathW = path_base + dir_data
os.chdir(pathW)
os.getcwd()

files_list = os.listdir(pathW)
files_list.sort()

In [274]:
files_list

['air_1afterbeer_roomlecture_20211218_174837.csv',
 'air_1aftercoffee_roomjose_20211218_203539.csv',
 'air_1aftertomato_roomjosecold_20211218_220200.csv',
 'beer_1pilsner_roomjose_20211218_193618.csv',
 'beer_1pilsner_roomjosecold_20211218_212621.csv',
 'beer_1pilsner_roomlecture_20211218_173239.csv',
 'beer_2budweiser_roomjose_20211218_194306.csv',
 'beer_2budweiser_roomjosecold_20211218_213031.csv',
 'beer_2budweiser_roomlecture_20211218_173823.csv',
 'beer_3weissbier_roomjose_20211218_193938.csv',
 'beer_3weissbier_roomjosecold_20211218_213436.csv',
 'beer_3weissbier_roomlecture_20211218_174413.csv',
 'bread_1milchbrot_roomjose_20211218_200247.csv',
 'bread_1milchbrot_roomjosecold_20211218_221426.csv',
 'bread_1milchbrot_roomlecture_20211218_185145.csv',
 'bread_2vollkorn_roomjose_20211218_200613.csv',
 'bread_2vollkorn_roomjosecold_20211218_221725.csv',
 'bread_2vollkorn_roomlecture_20211218_191225.csv',
 'bread_3brown_roomjose_20211218_200907.csv',
 'bread_3brown_roomjosecold_20211218_222022.csv',
 'bread_3brown_roomlecture_20211218_190025.csv',
 'carrot_1_roomjose_20211218_205542.csv',
 'carrot_1_roomjosecold_20211218_220500.csv',
 'carrot_1_roomlecture_20211218_183007.csv',
 'cheese_1mix_roomjose_20211218_204559.csv',
 'cheese_1mix_roomjosecold_20211218_220817.csv',
 'cheese_1mix_roomlecture_20211218_191619.csv',
 'cheese_2soft_roomjose_20211218_204221.csv',
 'cheese_2soft_roomjosecold_20211218_221113.csv',
 'cheese_2soft_roomlecture_20211218_185545.csv',
 'coffee_1graycup_roomjose_20211218_202909.csv',
 'coffee_1graycup_roomjosecold_20211218_215219.csv',
 'coffee_1graycup_roomlecture_20211218_175524.csv',
 'coffee_2blackcup_roomjose_20211218_202204.csv',
 'coffee_2blackcup_roomjosecold_20211218_214925.csv',
 'coffee_2blackcup_roomlecture_20211218_180009.csv',
 'coffee_3whitecup_roomjose_20211218_202517.csv',
 'coffee_3whitecup_roomjosecold_20211218_214623.csv',
 'coffee_3whitecup_roomlecture_20211218_180401.csv',
 'cola_1_roomjose_20211218_201259.csv',
 'cola_1_roomjosecold_20211218_213831.csv',
 'cola_1_roomlecture_20211218_182146.csv',
 'cucumber_1_roomjose_20211218_205230.csv',
 'cucumber_1_roomjosecold_20211218_215547.csv',
 'cucumber_1_roomlecture_20211218_183447.csv',
 'gluehwein_1graycup_roomjose_20211218_192824.csv',
 'gluehwein_1graycup_roomjosecold_20211218_211804.csv',
 'gluehwein_1graycup_roomlecture_20211218_180811.csv',
 'gluehwein_2whitecup_roomjose_20211218_193203.csv',
 'gluehwein_2whitecup_roomjosecold_20211218_212150.csv',
 'gluehwein_2whitecup_roomlecture_20211218_181219.csv',
 'lemon_1_roomjose_20211218_205931.csv',
 'lemon_1_roomjosecold_20211218_222620.csv',
 'lemon_1_roomlecture_20211218_184545.csv',
 'orange_1_roomjose_20211218_210244.csv',
 'orange_1_roomjosecold_20211218_222331.csv',
 'orange_1_roomlecture_20211218_190639.csv',
 'sprite_1_roomjose_20211218_201822.csv',
 'sprite_1_roomjosecold_20211218_214231.csv',
 'sprite_1_roomlecture_20211218_182548.csv',
 'tomato_1_roomjose_20211218_204922.csv',
 'tomato_1_roomjosecold_20211218_215852.csv',
 'tomato_1_roomlecture_20211218_183904.csv']

In [275]:
# count max length of lines in the files
# for balancing afterwards
# linux shell cmd is used
list_of_flines= !wc -l {pathW+"*"} #get list of n_of lines in each file
list_of_flines = list(list_of_flines) #convert to usual list
# -1 bcoz last element is sum of all n_of lines
max_of_flines = max([int(list_element.split()[0]) for list_element in list_of_flines][:-1]) - 1
max_of_flines

600

In [276]:
upsample_ratio = 3

Xdf = pd.DataFrame([], columns=["time_ms", 
                                "B102NO2", "B302C2H5OH", "B502VOC", "B702CO", 
                                "TdegC", "RH", 
                                "label", "add_label", "condition"])

for fileN in files_list:
    file_info = fileN.split("_")
    label_c = file_info[0]
    add_label_c = file_info[1]
    condition_c = file_info[2]
    
    df_c0 = pd.read_csv(fileN)

    
##############################################    
#     df_c0 = pd.read_csv(files_list[10])
    n_of_add_samples = int(max_of_flines * upsample_ratio - df_c0.shape[0])


    time_ms_t    = np.linspace(start=df_c0.time_ms.max(), stop=df_c0.time_ms.max()+n_of_add_samples*100, num=n_of_add_samples, dtype=int)
    
    #Uniform augmentation
    #uniform(low=0.0, high=1.0, size=None)
#     B102NO2_t    = np.random.uniform(low=df_c0.B102NO2.min(), high=df_c0.B102NO2.max(), size=n_of_add_samples)
#     B302C2H5OH_t = np.random.uniform(low=df_c0.B302C2H5OH.min(), high=df_c0.B302C2H5OH.max(), size=n_of_add_samples)
#     B502VOC_t    = np.random.uniform(low=df_c0.B502VOC.min(), high=df_c0.B502VOC.max(), size=n_of_add_samples)
#     B702CO_t     = np.random.uniform(low=df_c0.B702CO.min(), high=df_c0.B702CO.max(), size=n_of_add_samples)
#     TdegC_t      = np.random.uniform(low=df_c0.TdegC.min(), high=df_c0.TdegC.max(), size=n_of_add_samples)
#     RH_t         = np.random.uniform(low=df_c0.RH.min(), high=df_c0.RH.max(), size=n_of_add_samples)
    
    #Normal augmentation
    #normal(loc=0.0, scale=1.0, size=None)
    B102NO2_t    = np.random.normal(loc=df_c0.B102NO2.median(), scale=df_c0.B102NO2.std(), size=n_of_add_samples)
    B302C2H5OH_t = np.random.normal(loc=df_c0.B302C2H5OH.median(), scale=df_c0.B302C2H5OH.std(), size=n_of_add_samples)
    B502VOC_t    = np.random.normal(loc=df_c0.B502VOC.median(), scale=df_c0.B502VOC.std(), size=n_of_add_samples)
    B702CO_t     = np.random.normal(loc=df_c0.B702CO.median(), scale=df_c0.B702CO.std(), size=n_of_add_samples)
    TdegC_t      = np.random.normal(loc=df_c0.TdegC.median(), scale=df_c0.TdegC.std(), size=n_of_add_samples)
    RH_t         = np.random.normal(loc=df_c0.RH.median(), scale=df_c0.RH.std(), size=n_of_add_samples)
    
    
    time_ms_t.shape    = (time_ms_t.shape[0],1)
    B102NO2_t.shape    = (B102NO2_t.shape[0],1)
    B302C2H5OH_t.shape = (B302C2H5OH_t.shape[0],1)
    B502VOC_t.shape    = (B502VOC_t.shape[0],1)
    B702CO_t.shape     = (B702CO_t.shape[0],1)
    TdegC_t.shape      = (TdegC_t.shape[0],1)
    RH_t.shape         = (RH_t.shape[0],1)

    df_c0u = pd.concat([df_c0, 
                        pd.DataFrame(np.hstack(
                            (time_ms_t, B102NO2_t, B302C2H5OH_t, B502VOC_t, B702CO_t, 
                             TdegC_t, RH_t)), columns=df_c0.columns)], 
                       axis=0)\
            .reset_index(drop=True)
##############################################


    feature_add_dict = {
        "label": label_c,
        "add_label": add_label_c,
        "condition": condition_c,
    } 
    df_c_upd = pd.concat([df_c0u, pd.DataFrame(feature_add_dict, index=df_c0u.index)], axis=1)
    Xdf = pd.concat([Xdf, df_c_upd], axis=0)

In [277]:
## line4: "_normal" or "_uniform"
filename_to_save = "xdf_20211218_cle_bal_upsx"+\
                    str(upsample_ratio)+\
                    "_normal"+\
                    ".csv"
path_add = "df_data/"
Xdf.to_csv(path_base + path_add + filename_to_save, index=False)

In [278]:
Xdf

,time_ms,B102NO2,B302C2H5OH,B502VOC,B702CO,TdegC,RH,label,add_label,condition
0,3873.0,38.000000,27.000000,118.000000,90.000000,23.000000,43.0,air,1afterbeer,roomlecture
1,4102.0,38.000000,26.000000,119.000000,90.000000,23.000000,43.0,air,1afterbeer,roomlecture
2,4336.0,38.000000,26.000000,118.000000,89.000000,23.000000,43.0,air,1afterbeer,roomlecture
3,4571.0,37.000000,27.000000,119.000000,90.000000,23.000000,43.0,air,1afterbeer,roomlecture
4,4795.0,38.000000,27.000000,118.000000,89.000000,23.000000,43.0,air,1afterbeer,roomlecture
...,...,...,...,...,...,...,...,...,...,...
1795,259255.0,70.334605,29.546237,116.774145,101.880279,22.674611,49.0,tomato,1,roomlecture
1796,259355.0,69.198683,28.263255,108.997140,102.088241,23.247111,49.0,tomato,1,roomlecture
1797,259455.0,68.339501,29.610425,117.822850,102.668717,22.979047,49.0,tomato,1,roomlecture
1798,259555.0,70.259676,30.154897,119.493928,102.372819,22.559825,49.0,tomato,1,roomlecture
1799,259656.0,69.814154,27.191343,111.422480,101.924101,22.575152,49.0,tomato,1,roomlecture

In [279]:
21*3*600*3

113400